apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  namespace: bluegreen
  labels:
    app: myapp
    version: green
spec:
  selector:
    matchLabels:
      app: myapp
      version: green
  template:
    metadata:
      labels:
        app: myapp
        version: green
    spec:
      containers:
      - name: myapp
        image: nginx:1.21
        ports:
        - containerPort: 80
